services:
  app:
    build:
      context: .
    runtime: nvidia
    user: "${UID:-1000}:${GID:-1000}"  # ホストユーザーのUID/GIDを使用
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - TZ=Asia/Tokyo  # タイムゾーン設定（cronの時刻を日本時間に）
    tty: true
    stdin_open: true
    volumes:
      - .:/app
    ipc: host
    restart: unless-stopped  # コンテナの自動再起動
